language: node_js
sudo: required
node_js:
  - 10
services:
  - docker

script:
  - docker build -t factlist/factlist-ui .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push factlist/factlist-ui;
    fi
